### ISSUE TITLE
The layout should be responsive

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/NDC_OG#15] opened 2019-05-02 12:41 UTC

**Comment by Bachibouzouk** [comment] 2019-05-02 13:50
@bmlancien - what do you mean by that? less than 0.1s reaction time for example?

**Comment by nesnoj** [comment] 2019-05-02 14:14
I think @bmlancien means that the site is displayed as intended on different systems/resolutions/.., so it adapts the content to the client. E.g. [Zurb Foundation](https://foundation.zurb.com/) is a responsive framework we're using in the StEmp apps.
[cf](https://en.wikipedia.org/wiki/Responsive_web_design)

**Comment by bmlancien** [comment] 2019-05-03 07:41
Exactly @nesnoj , this tool should at least be presentable on tablets. On the other hand, I think that mobile size is not the priority.

**Comment by Bachibouzouk** [comment] 2019-06-11 18:52
Closed by #34

**Closed by Bachibouzouk** 2019-06-11 18:52 UTC
